### PR TITLE
dev to feature

### PR DESCRIPTION
**Pull request by FWAJL**
@gsouvik : merging dev to feature branch. Do a `git pull` before coding.

### CODE REVIEW

**Comment by FWAJL** [comment]
@gsouvik : merge complete.

**Comment by gsouvik** [comment]
@FWAJL 
Well I created a separate branch "feature_popup" and had been coding on it for the last hour or so. I did a pull so everything must have been latest on my "dev" at that point. So I guess, when I do a pull the changes would come down to the dev branch, right? I would just have to merge them into my "feature_popup" to make it up-to-date with the coding which I already did with this branch. 
Thanks again,
Souvik

**Comment by FWAJL** [comment]
@gsouvik 

Merging from dev to feature_popup bring all the dev branch code updates to the feature branch. When you do `git pull`, it downloads the changes from the remote feature_popup branch to your local feature_popup branch.

Then it is up-to-date and you can push your commits. I hope you won't have conflicts. If you do, I'll try show you how to resolve them.

Remember thought it is easier to review small amount of code that works. Don't be afraid to commit your work small commits, making sure everything works at each commit.
Do you understand?

**Comment by gsouvik** [comment]
Hello @FWAJL 

Thank you for explaining that bit of information. also I went through the wiki again and tried my first push to remote "feature_popup" branch.

It returned me the following error - 
"To https://github.com/FWAJL/FieldWorkAssistantMVC.git
   ef65041..2c5856f  feature_popup -> feature_popup
fatal: Unable to create '/Library/WebServer/Documents/FieldWorkAssistantMVC/.git/refs/remotes/fieldgithub/feature_popup.lock': Permission denied
Unexpected end of command stream"

Could you please help me understand what the issue might be. Thanks again.
Souvik

**Comment by FWAJL** [comment]
@gsouvik 

Do `git branch` and right after `git status` and make a screenshot (or a copy of the Terminal content into a text file). Upload it here and I'll see what's going on. Thank you.

**Comment by gsouvik** [comment]
@FWAJL 
Here's the screenshot. The files which are tracked by git as not staged (and not committed) are actually not changed by me. However I did run a chmod command on the folder as my editor was complaining non-editable files. Could it be the issue. Thanks for all the help. 

git_status

**Comment by FWAJL** [comment]
@gsouvik 

Yes, you can run:
`cd ..`
`chmod -R 777 FieldWorkAssistantMVC`
`cd FieldWorkAssistantMVC`

So that all files have write access.

Can you go the next step and do:
`git add -A`
`git commit -m "Issue #XXX" -m "your work description"
`git push`

and enter credentials. See a screenshot of the whole thing. Thank you.

**Comment by gsouvik** [comment]
Hello @FWAJL 
Yes I followed those exact commands earlier also, but finally it worked when I used "sudo" with those, so I managed executing them as root. The push was successful. The screenshot looks like the attached. 
Thanks, 
Souvik
git_push

**Comment by FWAJL** [comment]
@gsouvik 

Good!

The command line can be done from the moment you open Terminal:
`sudo su-` (I think).

Then:
`cd YOUR_GIT_DIRECTORY`

Your `git push` should be only `git push`. Why do you have `git push fieldgithub feature_popup`?
Have you run the following command when you create the local branch? This link the local branch to the remote branch.
`git push --set-upstream origin feature_popup`

**Comment by gsouvik** [comment]
@FWAJL 
Actually I let git on my local identify https://github.com/FWAJL/FieldWorkAssistantMVC.git as "fieldgithub". I know "origin" is the more conventional name used. Can this create any issue on the remote? I'll use the command you've shared next time.
Thank you.

**Comment by FWAJL** [comment]
@gsouvik 

I see your commits so your method is fine too. I was just wondering about your syntax. Thank you.

**Pull request merged**
