### PR TITLE
dev to feature merge

### PR DESCRIPTION
**Pull request by FWAJL**

### CODE REVIEW

**Comment by FWAJL** [comment]
@gsouvik 

Merge ongoing. Please wait before pushing. Thank you.

**Comment by gsouvik** [comment]
@FWAJL 
Please let me know if I can pull now and start adding code again.
Thank you.

**Comment by FWAJL** [comment]
@gsouvik 

Tomorrow morning GMT+1 hopefully. Will notify you.

**Comment by FWAJL** [comment]
@gsouvik 

Please git pull in the meantime.

**Comment by FWAJL** [comment]
@gsouvik 

I have the merge ready on my offline machine. Will try to find the time to complete the merge tonight GMT+1 time.

Thank you for your patience.

**Comment by gsouvik** [comment]
@FWAJL 

Thank you for the information. I shall wait for the merge and start coding again once it is done.

**Comment by FWAJL** [comment]
@gsouvik 

Complete. `git pull` please.

Thank you.

**Pull request merged**
