### PR TITLE
Feature mapping merge to dev

### PR DESCRIPTION
**Pull request by FWAJL**

### CODE REVIEW

**Comment by FWAJL** [comment]
@damirius 

Merging in progress.

**Comment by FWAJL** [comment]
@damirius 

I see a bug: can you help with it?
screen shot 2015-03-10 at 07 06 09

Thank you.

**Comment by FWAJL** [comment]
@gsouvik 

I am having an issue with this merge where the map legends popup is not showing on the mapping branch. Can you have a look to see why? 

Thank you for your help.

**Comment by FWAJL** [comment]
@damirius 

Thank you for the fix. I will check it before completing the merge. We have one outstanding issue to solve before doing that.

**Comment by FWAJL** [comment]
@gsouvik 

If you can and find the problem, try to commit the possible fix to the mapping branch. Thank you.

**Comment by gsouvik** [comment]
@FWAJL 
Let me see if I can find it quickly, shall update you shortly. On a separate note, a similar issue happened on feature_popup branch yesterday and I found out a code block out of place which was there in the earlier versions before, but not in that version, strange.

**Comment by gsouvik** [comment]
@FWAJL 
The map legend popup was not working in the mapping branch, fixed it. Please check and let me know.
Thank you.

**Pull request merged**
